"""
Image-level Precision/Recall evaluation for this fire detection task.

Ground truth format:
    {"image.jpg": 0, "image2.jpg": 1}

Prediction format is the same and can be generated by predict_submit.py.
"""
import argparse
import json
from pathlib import Path


def load_binary_json(path: str) -> dict:
    with Path(path).open("r", encoding="utf-8") as f:
        data = json.load(f)
    return {str(k): int(v) for k, v in data.items()}


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate image-level fire predictions.")
    parser.add_argument("--gt", required=True, help="Ground-truth JSON path.")
    parser.add_argument("--pred", required=True, help="Prediction JSON path.")
    args = parser.parse_args()

    gt = load_binary_json(args.gt)
    pred = load_binary_json(args.pred)

    common = sorted(set(gt) & set(pred))
    if not common:
        raise SystemExit("No overlapping image names between gt and pred.")

    missing = sorted(set(gt) - set(pred))
    extra = sorted(set(pred) - set(gt))

    tp = sum(1 for name in common if gt[name] == 1 and pred[name] == 1)
    fp = sum(1 for name in common if gt[name] == 0 and pred[name] == 1)
    fn = sum(1 for name in common if gt[name] == 1 and pred[name] == 0)
    tn = sum(1 for name in common if gt[name] == 0 and pred[name] == 0)

    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0

    print(f"Images evaluated: {len(common)}")
    print(f"TP={tp} FP={fp} FN={fn} TN={tn}")
    print(f"Precision={precision:.4f}")
    print(f"Recall={recall:.4f}")
    print(f"F1={f1:.4f}")
    if missing:
        print(f"Missing predictions: {len(missing)}")
    if extra:
        print(f"Extra predictions ignored: {len(extra)}")


if __name__ == "__main__":
    main()
